pixi.lock, pyproject.toml
Using the date as a version number seems like a wrong decision
=> Version follows the version of pyarrow

pyarrow-stubs/parquet/__init__.pyi
Hi there! The latest version seems to have a regression, where `pyarrow.parquet` attributes are not found when running mypy. 
This fixes the issue on my machine - let me know if you'd like to approach this differently, I saw that this line was explicitly deleted between 10.0.1.9 and 17.0
=> import parquet.core into parquet __init__.py

pyarrow-stubs/__lib_pxi/table.pyi
Pyright reports the following correct code as an error:
```python
a = [{"asd": 1}]
pa.Table.from_pylist(a)
```
```
error: Argument of type "list[dict[str, int]]" cannot be assigned to parameter "mapping" of type "list[Mapping[str, Any]]" in function "from_pylist"
"list[dict[str, int]]" is not assignable to "list[Mapping[str, Any]]"
Type parameter "_T@list" is invariant, but "dict[str, int]" is not the same as "Mapping[str, Any]"
Consider switching from "list" to "Sequence" which is covariant (reportArgumentType)
```
This PR fixes this error by following the suggestion in the error report.
=> fix: from_pylist covariance

pyarrow-stubs/_csv.pyi
For reference see: https://arrow.apache.org/docs/python/generated/pyarrow.csv.ConvertOptions.html
=> Add include_columns parameter in ConvertOptions

pyarrow-stubs/parquet/core.pyi
* Add support for per-field compression specification 
* Add missing none compression value.
See https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetWriter.html and https://github.com/apache/arrow/blob/apache-arrow-17.0.0/python/pyarrow/_parquet.pyx#L1385
=> improve type annotations for parquet writer

pixi.lock, pyarrow-stubs/__lib_pxi/io.pyi, pyarrow-stubs/_csv.pyi, pyarrow-stubs/_dataset.pyi, pyarrow-stubs/_dataset_parquet.pyi, pyarrow-stubs/_feather.pyi, pyarrow-stubs/_fs.pyi, pyarrow-stubs/_hdfs.pyi, pyarrow-stubs/_json.pyi, pyarrow-stubs/_parquet.pyi, pyarrow-stubs/dataset.pyi, pyarrow-stubs/feather.pyi, pyarrow-stubs/orc.pyi, pyproject.toml
This makes use of the StrPath type hint helper present in _typeshed that typing stub libraries are allows to use in order to handle all (hopefully) the places where arrow can take a `str` or a `pathlib.Path` as an argument
=> Change various io related functions to support `StrPath` as a path input

pyarrow-stubs/_parquet.pyi, pyarrow-stubs/_stubs_typing.pyi, pyarrow-stubs/dataset.pyi, pyarrow-stubs/orc.pyi, pyarrow-stubs/parquet/core.pyi
Additionally, add the utility typealias `SingleOrList` that can be used in places where we want a concise type declaration but the there is a large union of types.
=> Add some more StrPath io parts that were overlooked.

pyarrow-stubs/_dataset.pyi, pyarrow-stubs/dataset.pyi
This should now support the examples in the docstring for partitioning.
=> Add missing partitioning typing case

pyarrow-stubs/compute.pyi
Fix the type hints for `pyarrow.compute.sort_indices` to line up with.
https://arrow.apache.org/docs/python/generated/pyarrow.compute.sort_indices.html#pyarrow-compute-sort-indices
Seems like it erroneously matched https://arrow.apache.org/docs/python/generated/pyarrow.compute.array_sort_indices.html before
=> fix incorrect type hints for compute.sort_indices

pyarrow-stubs/__lib_pxi/table.pyi
When you use the names argument in conjunction with the dictionaries you get the following error at runtime
```
ValueError: The 'names' argument is not valid when passing a dictionary
```
We can prevent that with an overload
=> disallow passing `names` as an argument to table when using dictionaries

pyarrow-stubs/__lib_pxi/types.pyi
Hey,
I ran into a mypy error and would like to fix it upstream.
This is from the docstring of `pyarrow.struct`.
```
import pyarrow as pa
from typing import List, Tuple
fields: List[Tuple[str, pa.DataType]] = [
("f1", pa.int32()),
("f2", pa.string()),
]
struct_type = pa.struct(fields)
```
To make the last line pass mypy `Iterable[Tuple[str, DataType]]` needs to be added to the stub.
The actual implementation is even more permissive, is that needed? I.e. `Iterable[Tuple[x]]` works as long as you can feed x into `pyarrow.field`.
(https://github.com/apache/arrow/blob/f9a6edac9f175de3ad993887470dd1dff4f151c1/python/pyarrow/types.pxi#L5195)
=> improve coverage for pyarrow.struct typehint

pyarrow-stubs/__lib_pxi/ipc.pyi, pyarrow-stubs/ipc.pyi
The item type of `pyarrow.lib.IpcReadOptions.included_fields` comes from underlying `CIpcReadOptions` definition https://github.com/apache/arrow/blob/313d11aa94c2be71142b55e3d8bb166d780c19c7/python/pyarrow/includes/libarrow.pxd#L1815
=> fix: ipc typing

pyarrow-stubs/__lib_pxi/array.pyi, pyarrow-stubs/__lib_pxi/table.pyi
"List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
Consider using "Sequence" instead, which is covariant
=> fix: should use Collection[Array] instead list[Array]

pyarrow-stubs/__lib_pxi/table.pyi
Discovered during https://github.com/narwhals-dev/narwhals/pull/2007
I worked around it with this, but seemed simple enough to upstream:
```py
def _type(self: pa.ChunkedArray[pa.Scalar[_DataType_CoT]]) -> _DataType_CoT:
if TYPE_CHECKING:
return self[0].type
return self.type
```
=> fix: Preserve generic in `ChunkedArray.type`

pyarrow-stubs/__lib_pxi/table.pyi, pyarrow-stubs/_stubs_typing.pyi
Fixes the blanket `mypy` ignore and 12x `pyright` warnings
There were two distinct problems
1. `NullableIterable[T]` overlapped in **every** case, since `Iterable[None]` matched all cases
2. `date | datetime` and `int | bool | float` each needed to share an overload
i. See [special cases](https://typing.readthedocs.io/en/latest/spec/special-types.html#special-cases-for-float-and-complex) if this was surprising - the others are simply [nominal subtypes](https://typing.readthedocs.io/en/latest/spec/concepts.html#nominal-and-structural-types)
=> fix: Avoid `chunked_array` overlapping overloads

pyarrow-stubs/_stubs_typing.pyi, pyarrow-stubs/compute.pyi
This is preferable to *nothing* as `pyright` currently turns the result into `Unknown`.
I don't think there would be a way to statically type this accurately
- https://arrow.apache.org/docs/python/generated/pyarrow.compute.if_else.html
- https://github.com/narwhals-dev/narwhals/blob/dc9fcaa99f179f26b98e81134dd4aab54d1bd462/narwhals/_arrow/series.py#L1115-L1126
=> fix: Add placeholder annotations to `pc.if_else`

pyarrow-stubs/_stubs_typing.pyi, pyarrow-stubs/compute.pyi
- Should fix a lot of the issues I mentioned in https://github.com/zen-xu/pyarrow-stubs/pull/177#issuecomment-2671293573
- I've left a lot of links in the commit descriptions, pointing to where/what
=> fix: Widen `Array` to `Array | ChunkedArray`

pyarrow-stubs/compute.pyi
> This is an alias for [`coalesce()`](https://arrow.apache.org/docs/python/generated/pyarrow.compute.coalesce.html#pyarrow.compute.coalesce).
- https://arrow.apache.org/docs/python/generated/pyarrow.compute.fill_null.html
- https://github.com/narwhals-dev/narwhals/blob/05e47b27ebe27b24196cee5956d07748d65a62ee/narwhals/_arrow/series.py#L675
=> fix: add `pc.fill_null`

pyarrow-stubs/__lib_pxi/table.pyi
As per the [docs](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.from_arrays):
> **arrays**: [list](https://docs.python.org/3/library/stdtypes.html#list) of [pyarrow.Array](https://arrow.apache.org/docs/python/generated/pyarrow.Array.html#pyarrow.Array) or [pyarrow.ChunkedArray](https://arrow.apache.org/docs/python/generated/pyarrow.ChunkedArray.html#pyarrow.ChunkedArray)
See also [the implementation](https://github.com/apache/arrow/blob/aac110d4ef105c671ff5f9224effd53ed629aa8a/python/pyarrow/array.pxi#L389) which supports either, and doesn't require they all be of the same type.
This means the following will now type check ok:
```
def mix(a: pa.Array, b: pa.ChunkedArray) -> pa.Table:
return pa.Table.from_arrays([a,b])
```
Rather than return the pyright …
=> fix: Allow Table.from_arrays to take a list containing a mix of Array and ChunkedArray

pyarrow-stubs/__lib_pxi/table.pyi
#187 incorrectly applied the change to `RecordBatch.from_arrays`.
This PR fixes that mistake, and applies the change to `Table.from_arrays`.
In addition `RecordBatch.from_arrays` has been corrected to only support `Array` as [per the docs](https://github.com/apache/arrow/blob/7e18764e1f0ce7afddb169863b6b2b35d26b75b2/python/pyarrow/table.pxi#L3469).
=> fix: from_arrays for both Table and RecordBatch

pyarrow-stubs/compute.pyi
- https://github.com/zen-xu/pyarrow-stubs/pull/181#issuecomment-2692698237
- https://github.com/narwhals-dev/narwhals/issues/2124
Reduces the errors for the module to **11** (originally **30**)
=> fix: resolve some `pa.compute` overlaps

pyarrow-stubs/__lib_pxi/table.pyi
Discovered after updating to `17.18`
- https://github.com/narwhals-dev/narwhals/pull/2113/commits/0237f7a97abd1f818b20638130d111904d6578f6#diff-e7f4d5fb87ef26f448fcf8288f6c1af28fb035413f3dfcab69242c8e19192736
- https://github.com/narwhals-dev/narwhals/actions/runs/13895880249/job/38876300911?pr=2113
Will mean that this code:
```py
tp = pa.dictionary(pa.int32(), pa.string(), ordered=True)
arr = pa.array(["a", "b"], type=tp)
s = pa.chunked_array([arr], type=tp)
```
Can be reduced to:
```py
tp = pa.dictionary(pa.int32(), pa.string(), ordered=True)
arr = pa.array(["a", "b"], type=tp)
s = pa.chunked_array([arr])
```
And still have the type preserved
=> fix: Include `Array` in `chunked_array` overload

pyarrow-stubs/__lib_pxi/array.pyi, pyarrow-stubs/__lib_pxi/scalar.pyi, pyarrow-stubs/__lib_pxi/types.pyi
I played around with extension types and found that `pyarrow-stubs` is missing both `JsonType` and `UuidType`.
Also, all -`Array` and -`Scalar` types of that are missing too.
(now I stumbled over [this](https://github.com/zen-xu/pyarrow-stubs/issues/193) issue which is only a few days old)
The problem that I face with this PR is that `ExtensionType` (and `ExtensionScalar` & `ExtensionArray`) IMHO somehow has to be generic over what `.as_py()` (or `.to_pylist()`) can return, since this literally can be anything. In practice only `UuidType`/`UuidScalar` *does* override this (to `UUID | None`), but I wasn't able to make that work for now.
Could you please have a look how to fix this? Sorry!
=> Add Scalar, Array and Type classes for Json & Uuid

pyarrow-stubs/__lib_pxi/array.pyi, pyarrow-stubs/__lib_pxi/scalar.pyi, pyarrow-stubs/__lib_pxi/types.pyi
Reverts zen-xu/pyarrow-stubs#194.
JsonArray and UuidArray were added in pyarrow=19.0, but this project has not yet tracked the latest version. So this PR needs to wait until pyarrow-stubs is adapted to 19.0.
=> Revert "Add Scalar, Array and Type classes for Json & Uuid"

pyarrow-stubs/compute.pyi
Follow-up to #184, resolves 20+ new warnings in `narwhals` on `17.19`
https://github.com/narwhals-dev/narwhals/pull/2233#issuecomment-2729925160
=> fix: Add missing `pc.equal` overload

pyarrow-stubs/__lib_pxi/table.pyi
Per the docs (https://arrow.apache.org/docs/python/generated/pyarrow.concat_tables.html)
> tables : iterable of pyarrow.Table objects
=> fix: Allow `Iterable[Table]` in `concat_tables`

pyarrow-stubs/__lib_pxi/table.pyi
Also being more consistent with `ArrayOrChunkedArray[Any]` everywhere
Discovered in
- https://github.com/vega/vega-datasets/blob/343b7101391a81190ba24e1e8d62a381d2fef3bd/scripts/species.py#L798-L799
=> fix: Allow `ChunkedArray` in `Table.set_column`

pyarrow-stubs/_fs.pyi
```py
_fs.pyi:18: error: Skipping analyzing "fsspec": module is installed, but missing library stubs or py.typed marker  [import-untyped]
_fs.pyi:18: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports 
Found 1 error in 1 file (checked 64 source files)
```
- https://github.com/fsspec/filesystem_spec/issues/625
- https://github.com/fsspec/filesystem_spec/pull/1676
=> chore: Ignore `fsspec` `[import-untyped]`

pyarrow-stubs/compute.pyi
Fixes 3 errors:
```py
compute.pyi:608:5 - error: Overload 1 for "bit_wise_and" overlaps overload 4 and returns an incompatible type (reportOverlappingOverload)
compute.pyi:608:5 - error: Overload 1 for "bit_wise_and" overlaps overload 5 and returns an incompatible type (reportOverlappingOverload)
compute.pyi:620:5 - error: Overload 3 for "bit_wise_and" will never be used because its parameters overlap overload 1 (reportOverlappingOverload)
```
Also covers all 6 of these signatures:
https://github.com/zen-xu/pyarrow-stubs/blob/483ce12bfb8c04329efda62615e3ce03f1e57249/pyarrow-stubs/compute.pyi#L645-L650
=> fix: Resolve `bit_wise_and` overlaps

pyarrow-stubs/compute.pyi
Fixes 5 errors:
```py
compute.pyi:1948:5 - error: Overload 1 for "list_value_length" overlaps overload 2 and returns an incompatible type (reportOverlappingOverload)
compute.pyi:2685:5 - error: Overload 1 for "list_element" overlaps overload 2 and returns an incompatible type (reportOverlappingOverload)
compute.pyi:2693:5 - error: Overload 1 for "list_flatten" overlaps overload 2 and returns an incompatible type (reportOverlappingOverload)
compute.pyi:2711:5 - error: Overload 1 for "list_parent_indices" overlaps overload 2 and returns an incompatible type (reportOverlappingOverload)
compute.pyi:2719:5 - error: Overload 1 for "list_slice" overlaps overload 2 and returns an incompatible type (reportOverlappingOverload)
```
=> fix: Resolve `list_*` overlapping overloads

pyarrow-stubs/__lib_pxi/table.pyi
- Follow-up to #197
- Noticed while writing up (https://github.com/narwhals-dev/narwhals/issues/2385)
- We already use it for `std`, `var` in (https://github.com/narwhals-dev/narwhals/blob/16427440e6d74939c403083b52ce3fb0af7d63c7/narwhals/_arrow/group_by.py#L81-L82)
=> fix: Include `VarianceOptions` in `TableGroupBy.aggregate`

pyarrow-stubs/__lib_pxi/scalar.pyi
> scalar.pyi:75:20 - warning: TypeVar "_AsPyTypeK" appears only once in generic function signature
>     Use "object" instead (reportInvalidTypeVarUse)
> scalar.pyi:85:20 - warning: TypeVar "_AsPyTypeK" appears only once in generic function signature
>     Use "object" instead (reportInvalidTypeVarUse)
Instead just using `int`, which should be all that is possible from:
https://github.com/zen-xu/pyarrow-stubs/blob/02552b81161d19d4aa71d8656b028eefac84612b/pyarrow-stubs/__lib_pxi/types.pyi#L154-L164
https://github.com/zen-xu/pyarrow-stubs/blob/02552b81161d19d4aa71d8656b028eefac84612b/pyarrow-stubs/__lib_pxi/types.pyi#L63-L70
=> fix: Resolve `Scalar.as_py` warnings for `DictionaryType`

pyarrow-stubs/compute.pyi
Fixes:
- https://github.com/narwhals-dev/narwhals/pull/2390#discussion_r2046472574
Default is specified in https://arrow.apache.org/docs/python/generated/pyarrow.compute.sort_indices.html
=> fix: Add default to `pc.sort_indices`

pyarrow-stubs/dataset.pyi
The pyarrow `dataset()` function can take as source a single `Table` or a single `RecordBatch`.
From [the docs](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.dataset.html):
_(List of) batches or tables, iterable of batches, or RecordBatchReader:_
(list of) in parentheses for me means that one can provide a single item, and the code backs it up too
https://github.com/apache/arrow/blob/45918a90a6ca1cf3fd67c256a7d6a240249e555a/python/pyarrow/dataset.py#L779-780
Fixes this type checking error:
```
tests/models/schema_test.py:125: error: No overload variant of "dataset" matches argument type "Table"  [call-overload]
model=TableModel(dataset=pads.dataset(source=pa.Table.from_pandas(table)),
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests/models/schema_test.py:125: note: …
```
=> allow `Table` or `RecordBatch` for dataset

pyarrow-stubs/_dataset.pyi
The first argment `schema` is missing in the two methods.
=> Fix type signatures of Fragment.to_batches() and Fragment.to_table().

pyarrow-stubs/__lib_pxi/types.pyi
closes #260
This change makes the generic type parameter for pyarrow.Field covariant. This allows for more flexible type-checking. For example, a Field[Int64Type] can now be assigned to a variable of type Field[DataType].
=> feat(types): Make Field type parameter covariant
